module RestaurantApp
{
  struct MenuItem
  {
    string food;
    unsigned short cost;
  };

  struct OrderItem
  {
    MenuItem item;
    unsigned short quantity;
  };

  typedef sequence<MenuItem> MenuList;
  typedef sequence<OrderItem> OrderList;
  
  struct Time
  {
    unsigned short year;
    unsigned short month;
    unsigned short day;
    unsigned short hours;
    unsigned short minutes;
  };

  struct Menu
  {
    unsigned short version;
    MenuList menuList;
  };

  struct Order
  {
    unsigned short menuVersion;
    OrderList orderList;
    string userId;
    unsigned short totalCost;
    Time orderTime;
    Time completionTime;
  };

  typedef sequence<Order> OrdersList;


  interface Menu_Int
  {
    Menu getMenu();
  };
  
  interface Order_Int
  {
    boolean placeOrder(in Order order);
    Order getActiveOrder(in string userId);
    OrdersList getPreviousOrders(in string userId);
  };

  interface Admin_Int
  {
    long getAdminKey(in string username, in string password);
    boolean setMenu(in MenuList menu, in long key);
    OrdersList getAllOrders(in long key);
    OrdersList getAllActiveOrders(in long key);
  };
};