module RestaurantApp
{
  exception Incorrect_Password{};
  exception Incorrect_Key{};

  exception No_Menu_Set{};

  exception Empty_Order{};
  exception Menu_Too_Old{};
  exception Incorrect_Order_Total{};
  exception Order_In_Progess{};

  exception No_Active_Order{};
  

  struct MenuItem
  {
    string food;
    unsigned short cost;
  };

  struct OrderItem
  {
    MenuItem item;
    unsigned short quantity;
  };

  typedef sequence<MenuItem> MenuList;
  typedef sequence<OrderItem> OrderList;
  
  struct Time
  {
    unsigned short year;
    unsigned short month;
    unsigned short day;
    unsigned short hours;
    unsigned short minutes;
  };

  struct Menu
  {
    unsigned short version;
    MenuList menuList;
  };

  struct Order
  {
    unsigned short menuVersion;
    OrderList orderList;
    string userId;
    unsigned short totalCost;
    Time orderTime;
    Time completionTime;
  };

  typedef sequence<Order> OrdersList;


  interface Menu_Int
  {
    attribute Menu menu;
  };
  
  interface Order_Int
  {
    attribute OrdersList orders;
    boolean placeOrder(in Order order) raises (Empty_Order, Menu_Too_Old, Incorrect_Order_Total, Order_In_Progess);
    Order getActiveOrder(in string userId) raises (No_Active_Order);
    OrdersList getPreviousOrders(in string userId);
  };

  interface Admin_Int
  {
    long getAdminKey(in string username, in string password) raises (Incorrect_Password);
    boolean setMenu(in MenuList menu, in long key) raises (Incorrect_Key);
    OrdersList getAllOrders(in long key) raises (Incorrect_Key);
    OrdersList getAllActiveOrders(in long key) raises (Incorrect_Key);
  };

  
};